### PR TITLE
Better names for SEO & consistent formatting

### PR DESCRIPTION
**Pull request by mbjoseph**
This PR is designed to address #36.

### CODE REVIEW

**Comment by mbjoseph** [comment]
How do these look @lwasser? Any changes? 

The script that converts these to markdown files will automatically append the language ("-python" or "-r") to the end of each filename just before the .md extension [here](https://github.com/earthlab/earthlab.github.io/blob/master/convert_notebooks.py#L28).

**Comment by lwasser** [comment]
cool -- so are you using the permalink front matter element to populate the actual link @mbjoseph ?  what i can't see here is how the yml front matter is rendered which will impact the actual live page and subsequent SEO!

**Comment by lwasser** [comment]
the only changes i'd consider - point-cloud and super computer are two words. So think about how people search. it's good to potentially hyphenate both words. i'll do a bit more digging just to ensure things haven't changed in the SEO world because they could have changed so that it understands how to unpack words like super computer.

**Comment by mbjoseph** [comment]
Currently links are generated from the category and file names, rather than permalinks, e.g., 

This markdown file: `2016-09-13-Pymodis-tutorial-python.md` --> `https://earthlab.github.io/python/Pymodis-tutorial-python/`

I'll wait to split up supercomputer and point cloud - but I'm happy to do so if you want!

**Comment by mbjoseph** [comment]
Ok looks like supercomputer is one word, but point cloud is usually two. I'm going to go ahead and merge.

**Pull request merged**
