### PR TITLE
Updated to include google maps api key

### PR DESCRIPTION
**Pull request by zschira**
Google maps was recently updated to require api key, so previous tutorial will not display google maps plots.

### CODE REVIEW

**Comment by auroraTDunn** [comment]
Be warned there will most likely more changes between now and the end of the year as they are shutting down several key API's. This effectively breaks alot of things we wanted to do.

**Comment by mbjoseph** [comment]
Tim do you have a suggestion for a way forward? Merge this and keep updating, or is there a better option?

**Comment by auroraTDunn** [comment]
I REALLY wish I did. Once I have this Fire stuff done for the ROI's office I plan on trying to define what is and what won't be available in much more detail as it will also effect some parts of Earth Engine when it comes to mapping the EE analytic's output. Jeff has been spending more time in EE then me lately but has been shying away from dealing with Google Earth's API in favor of just sending everything out to matplotlib or another python vis package for this very reason.

**Comment by mbjoseph** [comment]
I'm going to close this now. Feel free to reopen if a solution emerges.

**Pull request closed without merging**
