### PR TITLE
Code Recipe #4

### PR DESCRIPTION
**Pull request by matt-oak**
Python tutorial for computing statistics on buffered spatial points in raster data.

### CODE REVIEW

**Comment by mbjoseph** [comment]
Thanks - just a couple of suggestions to make this even more useful:

- I'd use the `data/front_range_dem.tif` file instead of the DEM that the script currently references (which most users won't have)
- Some images would help to clarify what is going on here, e.g., plotting the raster, the point, the radius, and a circle around the point with that radius.
- Currently the user can only specify one point, and it has to be in terms of the row and column of the array. A more typical application would be that a user has a Raster (GeoTIFF, say) with a known coordinate reference system, and coordinates in latitude/longitude, and a radius in meters or kilometers. It will take some work to get from lat/lon to grid cells, and to have circular buffers rather than the current square buffers (see image). For an R example, check out the [raster::extract](http://www.inside-r.org/packages/cran/raster/docs/extract) function. 

grid-points

- It would probably be better to wrap all of this into a function as well, so that we don't end up with global variables that have really common names like `coords`, `data`, etc.

**Comment by matt-oak** [comment]
New commit implements lat/lon input, images, and circular buffer

**Comment by mbjoseph** [comment]
Awesome. Nice job! 

I'm trying to run this locally, and it seems like you're using a different file than the one associated with the GitHub repo. On github we have "front_range_dem.tif" but in the notebook you're using "front_range_dem.tiff". There seems to be some compatibility stuff going on - I can't get it to work with the data file embedded in the repo. Can you use that one instead? It might be confusing to have both "front_range_dem.tif" and "front_range_dem.tiff" in the data folder.

**Comment by matt-oak** [comment]
Adjusted notebook so it uses the proper file existing on the repo.

**Comment by matt-oak** [comment]
Fixed the location of the circle by using UTM coordinates. Sorry for my confusion, utilizing the UTM coordinates makes a lot more sense to me now, especially using that with QGIS to view the data/coordinates.

**Comment by mbjoseph** [comment]
Well done!

**Pull request merged**
